version: "3.7"

services:
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: log-analyzer
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 4000:4000
volumes:
  pgdata:
    driver: local
